# This workflow creates a release using goreleaser
# via the 'make release' command.

name: Create release

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 
permissions:
  contents: write

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.release_tag }}
      - name: Make release
        run: |
          make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

